
cc_library(
    name = "tensorflowlib",
    srcs = glob(["lib/*.dylib"]),
    hdrs = glob(["include/tensorflow/c/*.h"]),["include/tensorflow/c/eager/c_api.h"],
    visibility = ["//visibility:public"],
)