
cc_library(
    name = "tensorflowlib",
    srcs = glob(["lib/*.dylib"]),
    hdrs = ["include/tensorflow/c/eager/c_api.h","include/tensorflow/c/c_api.h", "include/tensorflow/c/c_api_experimental.h", "include/tensorflow/c/tf_attrtype.h", "include/tensorflow/c/tf_datatype.h", "include/tensorflow/c/tf_file_statistics.h", "include/tensorflow/c/tf_status.h", "include/tensorflow/c/tf_tensor.h"],
    visibility = ["//visibility:public"],
)